export const PROJECT_ACTION_TYPES = {
  SET_PLAYER_STATUS: 'SET_PLAYER_STATUS',
  UPDATE_PATTERNS: 'UPDATE_PATTERNS',
  SET_SAMPLE: 'SET_SAMPLE',
  UPDATE_SAMPLE: 'UPDATE_SAMPLE',
  UPDATE_SAMPLE_SETTINGS: 'UPDATE_SAMPLE_SETTINGS',
  REPLACE_SAMPLE: 'REPLACE_SAMPLE',
  REMOVE_SAMPLE: 'REMOVE_SAMPLE',
  SET_BPM: 'SET_BPM',
  SET_PATTERN_LENGTH: 'SET_PATTERN_LENGTH',
  SET_PROJECT: 'SET_PROJECT',
  RESET_STATE: 'RESET_STATE',
};
